### ISSUE TITLE
Suggestions(?)

### ISSUE THREAD

**Issue by mmmilord** [rejahtavi/rfp2#1]
Hey! First off, I'm really glad to see you continue/improve on what donbruce made. I love this mod and always wanted to include it but trying to make it work with other mods I could never bring myself to fully use it, that being said, what you state the second revision of the mod will do will solve all those issues.

Havent used the new version of the mod yet, since it just got updated on curseforge. Can it disable rendering itself entirely when sneaking/swimming? That would solve the problems of using it aside Mo'Bends and seeing a floating head. The other main problem is block-breaking with any block item in hand (ex, dirt/wood), because of the position/camera angle it sways violently back and forth in the players face which causes nausea, "Improved conflict lists for disabling parts of the mod when specific items are held " so I assume the mod can disable rendering of arms when for example holding any placeable full block? Or maybe just the breaking part? Not sure if the latter is able to be detected though. If it can already do these things, my apologies, that's great it makes using both mods actually playable!

Much appreciated

**Comment by rejahtavi** [comment]
Disabling when sneaking/swimming should actually be pretty easy to do, and can be made optional in the config file. I shouldn't even have to do anything specific for Mo'Bends in that case (inter-mod compatibility stuff is a lot trickier to do than detecting vanilla statuses).

It may be a while before the next release but I'll add this to my to-do list.

**Comment by mmmilord** [comment]
Thanks for the quick response, that sounds great. Lookin forward to it. I'll try out the current build, but I'll post a video for you so you can see what I mean exactly by it when I get some free time! :)

**Comment by rejahtavi** [comment]
Had some time to poke at RFP2 today. Release 1.1.0 is up, and it has checks for sneaking, swimming (2 modes), and holding any item. Please check it out when you have a minute and let me know what you think :)

**Comment by rejahtavi** [comment]
As I haven't heard anything back in a few days, I'm going to go ahead and close this issue. I hope you enjoy the mod! Thanks!
