### ISSUE TITLE
ido (swimming and crawling for 1.12.2)

### ISSUE THREAD

**Issue by Yekul10** [rejahtavi/rfp2#11]
Ido is a great mod that brings 1.14 swimming and crawling to 1.12.2. Yet with this (also awsome) mod enabled, the visuals go weird when swimming and crawling. There is also this weird jitter when I sneak. I don't know what that's about.
It would be nice if you're head wasn't in the way when you swim or crawl. Maybe first person render could be disabled when swimming or crawling is activated?

**Comment by rejahtavi** [comment]
There is already an option for this in the compatibility settings.

Bring up the main menu and go to Mod Options -> Real First Person 2 -> Compatability.

Here you should find "disable when sneaking" and "disable when swimming" options. There is also an option to make the swimming checks more aggressive (have to completely get out of the water to turn RFP2 back on)

Not sure about the crawling piece; if crawling counts as a type of sneaking the existing options may already work. Try it out and let me know what you find.

**Comment by simplebunsen** [comment]
For swimming, disabling it works, even without agressive detection. Crawling is unaffected by both options though.

**Comment by rejahtavi** [comment]
Finally had some time this weekend to have a poke at the code. Unfortunately Ido doesn't provide an easy way for me to detect whatever it is doing to the player model from RFP2 (there's no api), so I won't able to fix this easily, unfortunately.

**Comment by Kaydax** [comment]
@rejahtavi I will be adding an API for people to use in a quick update I will be releasing soon. Just tell me what you need and I can get it added. This is just a simple solution to the issue before I completely rewrite how ido handles its animations
