### ISSUE TITLE
PlayerFormLittleMaid compatibility

### ISSUE THREAD

**Issue by thregium** [rejahtavi/rfp2#12]
**Versions**
Minecraft = 1.12.2
Forge = 14.23.5.2838
RFP2 = 1.2.2

modchulib = v21a
PFLM = v36
PFLM models = v30a

**Describe the bug**
When I installed RFP2 and PFLM together, the viewing point is above the head of the model. I tried to adjust scale and it works normally when I'm seeing forward,  but with higher scale, viewing point sets inside the head when I'm seeing lower positions.
These things are happening similarly among all of the models including additional modelsets.

![2019-08-12_01 38 16](https://user-images.githubusercontent.com/35164579/63167722-12bf3580-c06d-11e9-9530-0ddf18201ece.png)

default model with default size

![2019-08-12_01 38 58](https://user-images.githubusercontent.com/35164579/63167723-1357cc00-c06d-11e9-80a4-8b32b7d41c80.png)

additional model with default size

![2019-08-12_01 39 56](https://user-images.githubusercontent.com/35164579/63167725-1357cc00-c06d-11e9-893a-9eab5ba91e72.png)

additional model with 1.6x size

**Comment by rejahtavi** [comment]
Unfortunately this mod seems to replace the entire player model class, and doesn't give me an easy way to manipulate it without redoing chunks of the main mod specifically for the new model. Unfortunately that means this would take far too much time & effort to fix. Apologies!
