### ISSUE TITLE
Conflicts with HammerCore

### ISSUE THREAD

**Issue by DomDuncan1** [rejahtavi/rfp2#13]
**Versions**
Minecraft = 1.12.2
Forge =forge-1.12.2-14.23.5.2768
RFP2 = Jul 27, 2019

**Does the bug happen when only RFP2 is installed?**
Yes

**Describe the bug**
When loading up a world, the whole screen turns light blue (I'm color deficient).

**How To Reproduce**
Put the HammerCore and RPF2 in mods folder.

**Expected behavior**
Loading into the game is normal until you try to load up a map.

**Screenshots**
![Screenshot (4)](https://user-images.githubusercontent.com/54045984/62904953-572d9700-bd36-11e9-8cb4-69abfc38cbda.png)
![Screenshot (3)](https://user-images.githubusercontent.com/54045984/62904958-5b59b480-bd36-11e9-913d-3cb81a5299db.png)
![2019-08-12_19 18 50](https://user-images.githubusercontent.com/54045984/62904964-5e54a500-bd36-11e9-98bf-88db05e49eba.png)
![Screenshot (8)](https://user-images.githubusercontent.com/54045984/62905084-eb97f980-bd36-11e9-98d4-d9dfeae5966c.png)
[crash-2019-08-12_19.22.15-client.txt](https://github.com/rejahtavi/rfp2/files/3494693/crash-2019-08-12_19.22.15-client.txt)

**Comment by DomDuncan1** [comment]
Most recent version of HammerCore*

**Comment by rejahtavi** [comment]
Just tried this with the latest version (2.0.4.9) which is slightly newer than the one you tried it with. Could not reproduce. Please retry; if it's still happening, please post your minecraft logs somewhere like pastebin and send me a link. Thanks!

**Comment by rejahtavi** [comment]
Haven't heard back with more info. Closing.
