### ISSUE TITLE
Incompatibility(?) with Armourers' Workshop

### ISSUE THREAD

**Issue by M0DSteam** [rejahtavi/rfp2#15]
**Versions**
Minecraft = 1.12.2
Forge = 2814
RFP2 = 1.2.3

**Does the bug happen when only RFP2 is installed?**
YES

**Describe the bug**
The mod works pretty well with AW, except for any headwear, as it renders the whole thing and looks awful

**How To Reproduce**
Just install the latest version of [Armourer's Workshop](https://www.curseforge.com/minecraft/mc-mods/armourers-workshop/files/2741765) along with RFP2, open the game and wear any kind of headwear

**Expected behavior**
The headwear should render, for example: If you equip a helmet, the whole thing renders where the head should be, making it almost impossible to see.

**Screenshots**
![](https://i.imgur.com/iRz2dPa.png)

![](https://i.imgur.com/LSWvoJT.png)

**Comment by rejahtavi** [comment]
I took a look in to AW and didn't see a quick or easy way for me to fix this from the RFP2 side alone. I've opened a feature request with AW here: [https://github.com/RiskyKen/Armourers-Workshop/issues/308](https://github.com/RiskyKen/Armourers-Workshop/issues/308)

If they have a way for me to resolve this, i'll let you know.

**Comment by RiskyKen** [comment]
@M0DSteam I believe this should work http://plushie.moe:8080/job/Armourers-Workshop-Dev/493/ This is a dev build so there are new blocks that are unfinished, just ignore them.

The next build public will be in a month or 2 so feel free to use this one until then. If you have any issues with it just give me a poke, there are always new dev build getting posted on the [AW Discord](https://discord.gg/5Z3KKvU ). :smile: 

@rejahtavi Had support already for RFP1 just did not know it had been updated.
