### ISSUE TITLE
Ido now has an API (& a config) - could you take another look at compatibility?

### ISSUE THREAD

**Issue by floral-qua-floral** [rejahtavi/rfp2#18]
Since version 1.1.0, Kaydax's [Idō](https://github.com/Kaydax/Ido) mod has functionality that should allow for compatibility between it and RFP2. Specifically, Idō now has an API that RFP2 should be able to check to determine whether the player is swimming or crawling. Furthermore, Idō has received a config file that allows users to disable certain functionality, so even without modifications to RFP2, complete compatibility is now available. By turning off Crawling in Idō and turning on Disable When Swimming in RFP2, there will be no more conflict, immediately resolving all incompatibility - however, RFP2 still refuses to load when Idō is detected. Removing Idō from the list of disabling mods is all that would really be necessary to restore compatibility, if you do not have the time to add proper API integration with Idō.

My apologies for making a new thread about this, by the way - I haven't seen any comment from you about Idō's addition of an API or its new config, so I am uncertain if you have heard the news or not. I would have chosen to use the old Idō thread, but I couldn't find an option to re-open it, and now that this is a perfectly fixable issue I do feel it should be in an open thread. Thanks!

**Comment by rejahtavi** [comment]
Fixed in 1.3.1!
<3
