### ISSUE TITLE
CarryOn Conflict (mod compatibility)

### ISSUE THREAD

**Issue by KenyMylankca** [rejahtavi/rfp2#2]
can you make it compatible with Carry On mod please? Thanks!
![aaa](https://user-images.githubusercontent.com/41585837/57584039-981bd280-74df-11e9-81e4-893e5cdff9ed.png)
Minecraft: 1.12.2
RealFirstPerson2-1.12.2-1.0.2
CarryOn+MC1.12.2+v1.12.1

**Comment by rejahtavi** [comment]
This will involve making an optional dependency on CarryOn, then checking to see if the player is carrying something. I haven't done any inter-mod compatibility checks yet, so I'm going to take this as a challenge. It may be a few weeks before I shift gears back into working on RFP2 (trying to finish getting a private mod pack together for some friends who are new to modded MC right now), but I will see what I can figure out when I do.

**Comment by KenyMylankca** [comment]
if you can fix this, it gonna be lovely and we would be very very happy and thankful to you. hope you fix it!
get luck!

**Comment by rejahtavi** [comment]
Resolved in the latest release. 1.2.0 should come out by the end of the weekend!

**Comment by KenyMylankca** [comment]
Thanks a lot!
