### ISSUE TITLE
Ido Support

### ISSUE THREAD

**Issue by GamingMidi** [rejahtavi/rfp2#22]
Ido has had an api for a long time and a few people have opened a request about it, I'm kind of reopening this i guess?... https://github.com/rejahtavi/rfp2/issues/18

Can you add support for ido?

**Comment by mmmilord** [comment]
Like a year ago, I specifically asked for RFPR to be disabled as an opt when crouching/swimming so it would work out of the box with mods like Mo'Bends and Ido so it should be okay if it loads itself. Hope rejahtavi sees it at some point ^^

**Comment by rejahtavi** [comment]
After a long hiatus due to personal life chaos, I'm back to coding.

I will be making the conflict list totally bypassable in the next version, and better yet, I plan to fully support Ido in RFP2. Version 1.3.0 should be out in the next couple weeks.

Thank you for your patience.

-- Rejah <3

**Comment by mmmilord** [comment]
I've been using ver 1.2.2 which doesn't have the auto disable detection and works for the most part with both of them running as mentioned b4. Glad to see you're alright! :) Take your time with it.

**Comment by rejahtavi** [comment]
Fixed in 1.3.1!
<3
