### ISSUE TITLE
Head baubles show in first person

### ISSUE THREAD

**Issue by maxim0p** [rejahtavi/rfp2#23]
**Versions**
Minecraft = 1.12.2
Forge = forge-14.23.5.2847
RFP2 = 1.2.3

**Does the bug happen when only RFP2 is installed?**
YES 

**Describe the bug**
Baubles has a head slot, similar to a helmet slot, some baubles from mods have 3D rendering. (Artifacts mod for example). If there is a 3D rendered head bauble, then it will show in first person. This happens with any mod that has a 3d rendered head bauble.

**How To Reproduce**
Download a bauble mod with 3d rendering head bauble, like the [Aritfacts](https://www.curseforge.com/minecraft/mc-mods/artifacts) mod, alongside rfp2 and you will see that it shows up, obscuring the players view.

**Expected behavior**
I expected the head bauble to not be visible, as a regular helmet wouldn't be visible.

**Screenshots**
https://imgur.com/a/3RJHpmQ

**Comment by rejahtavi** [comment]
Apologies for the delayed response, I've had some personal life chaos that resulted in me taking a hiatus from modding for a while. I'm actively developing RFP2 again now, and will take a look into the baubles issue.

A new version will be coming out soon, v1.3.0, but it is focusing on refactoring a few things and preparing for more features. It won't have a baubles fix but future versions might, depending on what I find with the baubles source. I will update this thread again once I've had a chance to confirm whether I can fix this or not.

Thank you for your patience,

-- Rejah <3

**Comment by rejahtavi** [comment]
Fixed in v1.3.2!
-- Rejah <3
