### ISSUE TITLE
More Player Models 1.12.2 Compatibility

### ISSUE THREAD

**Issue by LittleNom** [rejahtavi/rfp2#3]
**Versions**
Minecraft = 1.12.2
Forge =1.12.2-14.23.4.2836
RFP2 =1.0.2

Looking down while using "More player models" the head layer of the Skin renders during first person and gets in the way.

I think this was an issue that was decided to let the maker of "More player models" to fix before,
Though i'd feel much more comfortable if i asked and had a response from you saying if you could fix this issue or not, Thank you for your hard work!
![2019-05-12_12 01 07](https://user-images.githubusercontent.com/50555119/57586841-938bf580-74b0-11e9-82c1-6239c1b83f81.png)

**Comment by rejahtavi** [comment]
Hm, this will involve making an optional dependency on "More Player Models" and hiding any head layers it adds when RFP2 is switched on. I haven't done optional dependency work yet so it's going to take some figuring out but I will give it a shot when I get back to updating RFP2. (Right now I am trying to finish putting together a private pack to introduce some friends to modded MC). Something else to keep in mind is that, depending on how MPM is coded, this may or may not be possible without modifications to MPM.

What version of MPM are you using? Thanks.

**Comment by LittleNom** [comment]
> 
> 
> Hm, this will involve making an optional dependency on "More Player Models" and hiding any head layers it adds when RFP2 is switched on. I haven't done optional dependency work yet so it's going to take some figuring out but I will give it a shot when I get back to updating RFP2. (Right now I am trying to finish putting together a private pack to introduce some friends to modded MC). Something else to keep in mind is that, depending on how MPM is coded, this may or may not be possible without modifications to MPM.
> 
> What version of MPM are you using? Thanks.

Well thats okay! Heres hoping things work out smoothly once you try working with it!
The version i'm using should be the latest one, "1.12.2 (18jan18)"
It doesnt exactly have a number for itself other than the date, I downloaded this from Curseforge if that helps

**Comment by rejahtavi** [comment]
Finally got around to digging into this when I added compatibility for Morph.

Unfortunately MPM is closed source and does not publish an API for other mods to interact with it in a clean way, so I currently have no way of fixing this from my side.

**Comment by LittleNom** [comment]
Awhh ohwell, Thanks for looking into it!

**Comment by ThePoshTux** [comment]
I completely understand why you won't be chasing "compatibility" with MPM and have created an auto-disable function. However, from my point of view, the viewing of the hat layer was working as intended and the two mods are perfectly compatible. Would it be possible to have an optional overrule to the MPM blacklist in later versions? I have rolled back a version of RFP2 for now.
