### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by TurkishAhmet4545** [rejahtavi/rfp2#45]
Can we see any bugs if we use this mod with an animation mod ?

Such as epic fight,mo bends etc.

**Comment by ekiplier** [comment]
Definitely don't use it with Epic Fight.

It works with Mo'bends but it's a bit glitchy. However, you can mess with the player offset in the configs

**Comment by TurkishAhmet4545** [comment]
> Definitely don't use it with Epic Fight.
> 
> It works with Mo'bends but it's a bit glitchy. However, you can mess with the player offset in the configs

Thanks.
