### ISSUE TITLE
Renders own head in first person when Obfuscate library is installed

### ISSUE THREAD

**Issue by wolfboyft** [rejahtavi/rfp2#5]
That's this: https://minecraft.curseforge.com/projects/obfuscate

**Comment by rejahtavi** [comment]
Hmm, it looks like they don't share their source code, so I can't look in to this and see what exactly they're doing that's causing the problem. However, it would appear, based on your description of the issue, that they are replacing or modifying the player doRender() routine in a way that does not honor the "playerModel.bipedHead.isHidden" property that i set before I call the vanilla player renderer.

As such there is not much I can do about this -- I would either need to see their source to know exactly how to check for and deal with the specific case of having obfuscate installed, or obfuscate would need to be rewritten in a way that honors the vanilla doRender() properties when RFP2 calls them.

As obfuscate seems to still be in early development, it could also simply be a bug in the way they have implemented their routines, so I would recommend opening an issue with their project. As it is I'm afraid there's not much I can do, unfortunately.
