### ISSUE TITLE
Cosmetic Armor renders over player view

### ISSUE THREAD

**Issue by IronPiston** [rejahtavi/rfp2#6]
**Versions**
Minecraft = 1.12.2
Forge = 14.23.5.2838
RFP2 = 1.1.0

**Does the bug happen when only RFP2 is installed?**
YES

**Describe the bug**
Wearing cosmetic armor using Cosmetic Armor Reworked causes the cosmetic armor to render over the player's head, obstructing your view.

**How To Reproduce**
Put any armor (specifically a helmet), and look down towards your feet

**Expected behavior**
Cosmetic armor should render like normal armor, while not causing any obstruction.

**Screenshots**
![2019-06-13_17 58 14](https://user-images.githubusercontent.com/11603684/59472661-d8cf7a00-8e04-11e9-9d12-7aa37abb296d.png)
![2019-06-13_17 58 17](https://user-images.githubusercontent.com/11603684/59472664-da993d80-8e04-11e9-82d2-b2dcad369d91.png)

**Comment by rejahtavi** [comment]
Thanks for the report. I'll take a look at this when I have some time to update the mod. IRL has me swamped at the moment!

**Comment by rejahtavi** [comment]
Resolved in the latest release, 1.2.0 should come out by the end of the weekend!
