### ISSUE TITLE
Disables itself with Aether Legacy installed when I died.

### ISSUE THREAD

**Issue by simplebunsen** [rejahtavi/rfp2#8]
Should be pretty straightforward, here's the log that contains all the info I have.
https://paste.dimdev.org/editijuvub.md

**Comment by simplebunsen** [comment]
Update: Removed aether and the same still happened 
https://paste.dimdev.org/agarugohis.md

**Comment by rejahtavi** [comment]
The next version will have the ability to ignore render thread errors. This means that whatever mods are causing this will no longer cause RFP2 to disable, but if that mod does not in turn handle the rendering error correctly, the game could crash.

Watch for 1.2.2 to be uploaded in a few days.

**Comment by simplebunsen** [comment]
Done that, and no problems so far as far as ingame is concerned. It does spam my console with literally hundreds of thousands of this message though :(
: com.rejahtavi.rfp2.RenderPlayerDummy.doRender() **IGNORING** exception:Index: 69, Size: 0

**Comment by rejahtavi** [comment]
Hahah, yeah I see the problem. That line was supposed to go to the log only, not the chat box... Sorry about that. I will update it as soon as I get a chance.

**Comment by simplebunsen** [comment]
Thanks a ton! Rate limiting is a great idea, as it seemed to be going off every tick.

**Comment by rejahtavi** [comment]
The next release (should be uploaded in a few hours from this comment) will no longer log errors to the player's chat when the "ignore errors" option is turned on, and it will only log errors once per minute to the main minecraft log.

**Comment by rejahtavi** [comment]
Forgot to say, I cannot reproduce this issue when I install the Aether Legacy pack; please try it on yours and let me know if the debug alterations have resolved the issue. (You might also try updated the mod pack and seeing if it still produces the errors). Thanks!

Post here if it still happens and I will reopen the issue if necessary.
