### ISSUE TITLE
1.13.2 (Forge) / 1.14.3 (Fabric) update?

### ISSUE THREAD

**Issue by kotauskas** [rejahtavi/rfp2#9]
The title says it all. Porting to Forge 1.13.2 is near to trivial, and porting to Fabric is quite easy. Is something like that planned?

**Comment by rejahtavi** [comment]
I do not play 1.13.2 neither do any of the people I made this mod for, so I do not have any plans at this time to perform an update. However, I would happily accept a pull request for a new branch if someone else wants to maintain it.

**Comment by rejahtavi** [comment]
Just a heads up, it was recently brought to my attention that someone has made a similar mod for 1.14+ with Fabric:
https://www.curseforge.com/minecraft/mc-mods/first-person-model
